apiVersion: v1
kind: Service
metadata:
    name: nginx-svc
    namespace: my-namespace
spec:
    type: NodePort
    ports:
    - port: 80
      nodePort: 31009
      protocol: TCP
    selector:
        app: nginx-pod
        