apiVersion: v1
kind: Service
metadata:
    name: wordpress-svc 
    labels:
      app: wordpress
spec:
    ports:
        - port: 80
          nodePort: 31001
          protocol: TCP
    selector:
        app: wordpress
    type: NodePort